### ISSUE TITLE
Task is frozen

### ISSUE THREAD

**Issue by Quatra** [Schlumberger/vsts-chromium-task#2]
Hello,

I've just installed the task (version 0.1.15) into VSTS.
I am using the Hosted Agent VS2017.
I've put the default settings for the Unpack To field ($(System.DefaultWorkingDirectory)).
After 10 minutes, the task is not finished and I have no information in the logs.

Do I need to use a different path?

Thanks,

**Comment by helgejfo** [comment]
I have only tested this extension to work on the regular Hosted agent and not on the VS2017 one. Will have a quick look and report back.

**Comment by helgejfo** [comment]
It seems to work for VS2017 as well, but it is extremely slow 15-20 minutes. The problem is downloading the binaries, so when I get the time I will have a look at leveraging the VSTS Tools Installer feature, which allows caching the binaries even for Hosted agents.
